
[default_function(l4xi_linux_default_handle), uuid(0xd00)]
interface l4xi
{
  /*
   * Called from the startup thread to the main thread.
   */
  [oneway]
  void linux_main_startup();

  /*
   * Called from any thread to the startup thread to exit L4Linux.
   */
  [oneway]
  void linux_main_exit();

  /*
   * Dummy function to emulate to exception buffer.
   */
  void large_enough_message_buffer(unsigned long v1, unsigned long v2,
                                   [in, out, ref, max_is(100)] char *s);
};
